#!/bin/sh
branch_name=$(git branch --show-current)
pattern="^(feat/|fix/|release/|chore/)"

if ! [[ $branch_name =~ $pattern ]]; then
    echo "ERROR: Your branch name does not meet the required pattern (feat/, fix/, release/, chore/)."
    echo "To rename your branch, use the following command, replacing 'new-branch-name' with the correct format:"
    echo "git branch -m new-branch-name"
    exit 1
fi

yarn lint:fix
