#!/bin/sh

branch_name=$(git branch --show-current)
pattern="^(feat/|fix/|release/|chore/)"
ignore_branches="^(main|dev)$"

if [[ $branch_name =~ $ignore_branches ]]; then
    exit 0 # Ignore the check if the branch is main or dev
fi

if ! [[ $branch_name =~ $pattern ]]; then
    echo -e "\033[31mERROR: Your branch name '$branch_name' does not meet the required pattern (feat/, fix/, release/, chore/).\033[0m"
    echo "Please rename your branch before pushing. For example:"
    echo "git branch -m <new-name>"
    exit 1
fi