name: PR Automation Workflow

on:
  pull_request:
    branches:
      - release/*
      - fix/*

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.1.6

      - name: Check package.json
        uses: tj-actions/changed-files@v44.5.1
        id: package-json
        with:
          files: |
            package.json

      - name: Check CHANGELOG.md
        uses: tj-actions/changed-files@v44.5.1
        id: changelog
        with:
          files: |
            CHANGELOG.md

      - name: Verify Changes
        run: |
          MISSING_UPDATES=()
          if [[ "${{ steps.package-json.outputs.any_changed }}" == 'false' ]]; then
            MISSING_UPDATES+=("package.json")
          fi
          if [[ "${{ steps.changelog.outputs.any_changed }}" == 'false' ]]; then
            MISSING_UPDATES+=("CHANGELOG.md")
          fi
          if [ ${#MISSING_UPDATES[@]} -ne 0 ]; then
            echo "Error: The version should be updated on following files: ${MISSING_UPDATES[*]}"
            exit 1
          fi
